@startuml languages
' languages 単独 ER 図
entity "languages" as languages {
  * id : varchar(10) <<PK>>
  --
  name : text
  native_name : text
}

note right of languages
  Used as FK by:
  - root_accounts.mother_tongue_code
  - root_accounts.site_language_code
  - user_languages.language_id
end note
@enduml
